[lint]
select = ["E4", "E7", "E9", "F", "B"]
ignore = ["E501", "B008"]
unfixable = ["B"]
[lint.per-file-ignores]
"__init__.py" = ["E402"]
"**/{tests,docs,tools}/*" = ["E402"]

[lint.isort]
force-single-line = true

[format]
quote-style = "single"
